[package]
name = "roguelike"
version = "0.1.0"
edition = "2021"

[dependencies]
cgmath = "0.18.0"
sdl2 = { version = "0.37.0", default-features = false, features = ["image", "unsafe_textures"] }
thiserror = "2.0.5"
